package com.letsdata.commoncrawl.model.filerecords.types;

public enum DocumentRecordTypes {
    WARC_WARCINFO_PAYLOAD,
    WARC_HTTP_REQUEST_PAYLOAD,
    WARC_HTTP_RESPONSE_PAYLOAD,
    WARC_METADATA_PAYLOAD,
    WAT_WARCINFO_PAYLOAD,
    WAT_METADATA_WARC_WARCINFO_PAYLOAD,
    WAT_METADATA_WARC_REQUEST_PAYLOAD,
    WAT_METADATA_WARC_RESPONSE_PAYLOAD,
    WAT_METADATA_WARC_METADATA_PAYLOAD,
    WET_WARCINFO_PAYLOAD,
    WET_CONVERSION_PAYLOAD,
    WARC_ERROR,
    WAT_ERROR,
    WET_ERROR
}
